configure: specify how to run electrum-server
Otherwise:

$ electrum-server
Usage: electrum-server {start|stop|restart|status|getinfo|peers|numpeers|sessions|numsessions|banner_update}

$ electrum-server start
Starting server as daemon
/usr/local/bin/electrum-server: line 64: /var/log/electrum.log: Permission denied

$ sudo electrum-server start
Traceback (most recent call last):
  File "/usr/local/bin/run_electrum_server.py", line 4, in <module>
    __import__('pkg_resources').run_script('electrum-server==1.0', 'run_electrum_server.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/electrum_server-1.0-py2.7.egg/EGG-INFO/scripts/run_electrum_server.py", line 39, in <module>

  File "build/bdist.linux-x86_64/egg/electrumserver/__init__.py", line 2, in <module>
  File "build/bdist.linux-x86_64/egg/electrumserver/storage.py", line 24, in <module>
  File "build/bdist.linux-x86_64/egg/plyvel/__init__.py", line 6, in <module>
  File "build/bdist.linux-x86_64/egg/plyvel/_plyvel.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/plyvel/_plyvel.py", line 4, in __bootstrap__
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1172, in resource_filename
    self, resource_name
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1716, in get_resource_filename
    self._extract_resource(manager, self._eager_to_zip(name))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1746, in _extract_resource
    self.egg_name, self._parts(zip_path)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1239, in get_cache_path
    self.extraction_error()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1219, in extraction_error
    raise err
pkg_resources.ExtractionError: Can't extract file(s) to egg cache

The following error occurred while trying to extract file(s) to the Python egg
cache:

  [Errno 13] Permission denied: '/home/electrum'

The Python egg cache directory is currently set to:

  /home/electrum/.python-eggs

Perhaps your account does not have write access to this directory?  You can
change the cache directory by setting the PYTHON_EGG_CACHE environment
variable to point to an accessible directory.

Starting server as daemon